# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.3'
pod 'SwiftyJSON'
pod 'AlamofireImage', '~> 3.1'
pod 'NVActivityIndicatorView'
  # Pods for SwiftSample

  target 'SwiftSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
